name: wtf
on: [push, pull_request]
jobs:
  build:
    name: wtf
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.2', '7.3', '7.4']

    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      
      - name: Set PHP versions
        run: which php
        # run: update-alternatives --set php /usr/bin/php${{ matrix.php-versions }}

      - name: wtf
        run: php -v
