name: Testing-PHP-Versions
on: [push, pull_request]
jobs:
  build:
    name: Dummy CI Test
    runs-on: ubuntu-latest
    
  strategy:
    fail-fast: false
    matrix:
      php-versions: ['7.2']
    
  steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
  
    - name: PHP Version
      runs: php -v