name: wtf
on: [push, pull_request]
jobs:
  build:
    name: wtf
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.2', '7.3', '7.4']

    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Set PHP versions
        # run: which php
        run: sudo update-alternatives --set php /usr/bin/php${{ matrix.php-versions }}
      
      - name: Disable Xdebug
        run: sudo rm /etc/php/${{ matrix.php-versions }}/cli/conf.d/20-xdebug.ini
      
      - name: Show php config
        run: php -i

      - name: Cat PHP ini
        run: cat /etc/php/${{ matrix.php-versions }}/cli/php.ini
      
      - name: Cat Xdebug ini
        run: cat /etc/php/7.4/cli/conf.d/20-xdebug.ini
      
      - name: wtf
        run: php -v
